language: python

cache: pip

sudo: required

# http://docs.travis-ci.com/user/caching/#Arbitrary-directories
cache:
  directories:
  - src/.m2

services:
  - docker

# Upgrade to latest docker-engine
before_install:
  - sudo apt-get update -qq
  - sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" docker-engine
  - docker -v
  - pip install docker-compose
  - docker-compose -v
 
install:
  - ./bf build
  - ./build build
  - ./omero build
  - ./server build
  - ./web build

before_script:
  - git clone git://github.com/openmicroscopy/bioformats src/bf.git
  - git clone git://github.com/openmicroscopy/openmicroscopy src/omero.git

script:
  - ./bf up
  - ./build up
