#!/bin/bash

# build omero

set -eux

PATHDIR=`dirname $0`

if [ -n "${BUILD_NAME}" ]; then
    echo "BUILD_NAME is set to: ${BUILD_NAME}"

    SERVER_NAME="dev_${BUILD_NAME}_1"
    DOCKER_BIN="docker exec -it ${SERVER_NAME}"

    BF_PREFIX=/home/omero/bf.git
    OMERO_DIR=/home/omero/omero.git
    OMERO_PREFIX="${OMERO_DIR}/dist"

    source "${PATHDIR}/buildscripts/stop.sh"
    source "${PATHDIR}/buildscripts/remove_symlinks.sh"

    $DOCKER_BIN /bin/bash -c "${OMERO_DIR}/build.py build-dev"

    $DOCKER_BIN /bin/bash -c "${OMERO_PREFIX}/bin/omero admin rewrite"

    source "${PATHDIR}/buildscripts/add_symlinks.sh"
    #source "${PATHDIR}/buildscripts/start.sh"

else 
    echo "source BUILD_NAME/build.env"
fi

