omeroserver:
    extends:
        file: common-services.yml
        service: baseomero
    volumes:
        - "./${BUILD_NAME}/dist/OMERO.server:/home/omero/OMERO.server"
        - "./${BUILD_NAME}/data:/home/omero/data"
        - "${PWD}/${BUILD_NAME}/config/omero.config:/home/omero/omero.config"
    ports:
        - "4064:4064"
        - "4063:4063"
    extra_hosts:
        - "pg95:10.0.2.2"
