omerobuild:
    extends:
        file: common-services.yml
        service: baseomerobuild
    volumes:
        - "./${BUILD_NAME}/src:/home/omero"
    environment:
        - OMERO_PREFIX=/home/omero/omero.git/dist