redis:
    image: redis

omeroweb:
    extends:
        file: common-services.yml
        service: baseweb
    links:
        - redis
    volumes:
        - "./src/omero.git:/home/omero/src"
        - "./src/dist/OMERO.server:/home/omero/OMERO.py"
        - "./src/dist/static:/home/omero/static"
        - "${PWD}/config/omeroweb.config:/home/omero/omeroweb.config"
        - "./src/nginx/conf.d:/home/omero/conf.d"
    environment:
        - OMEROWEB_SRC=/home/omero/src/components/tools/OmeroWeb
        - OMERO_PY=/home/omero/OMERO.py

nginx:
    extends:
        file: common-services.yml
        service: basenginx
    links:
        - omeroweb
    volumes:
        - "./src/dist/OMERO.server:/home/omero/OMERO.server"
        - "${PWD}/src/nginx/conf.d:/etc/nginx/conf.d"
        - "./src/dist/static:/home/omero/static"
        - "./src/nginx/log:/var/log/nginx"
#        - "./src/nginx/sslcert:/etc/nginx/ssl"
    ports:
        - "80:80"
#        - "443:443"
