omeroserver:
    extends:
        file: common-services.yml
        service: baseomero
    volumes:
        - "./dist/OMERO.server:/home/omero/OMERO.server"
        - "./data:/home/omero/data"
        - "${PWD}/config/omero.config:/home/omero/omero.config"
    ports:
        - "4064:4064"
        - "4063:4063"
    extra_hosts:
        - "pg95:10.0.2.2"
