redis:
    image: redis

omeroweb:
    tty: true
    extends:
        file: common-services.yml
        service: baseweb
    links:
        - redis
    volumes:
        - "./src/omero.git:/home/omero/src"
        - "./src/mapr.git:/home/omero/mapr"
        - "./src/dist/OMERO.py:/home/omero/OMERO.py"
        - "./src/dist/static:/home/omero/static"
        - "${PWD}/config/omeroweb.config:/home/omero/omeroweb.config"
        - "./src/nginx/conf.d:/home/omero/conf.d"
    ports:
        - "4080:4080"
    env_file:
        - web.env

nginx:
    extends:
        file: common-services.yml
        service: basenginx
    links:
        - omeroweb
    volumes:
        - "./src/dist/OMERO.py:/home/omero/OMERO.py"
        - "./src/nginx/conf.d:/etc/nginx/conf.d"
        - "./src/dist/static:/home/omero/static"
        - "./src/nginx/log:/var/log/nginx"
#        - "./src/nginx/sslcert:/etc/nginx/ssl"
    ports:
        - "80:80"
#        - "443:443"
