redis:
    image: redis
    container_name: "redis"

omeroserver:
    extends:
        file: common-services.yml
        service: baseomero
    volumes:
        - "./${BUILD_NAME}/src:/home/omero"
    ports:
        - "4064:4064"
        - "4063:4063"
    extra_hosts:
        - "pg95:10.0.2.2"

omeroweb:
    extends:
        file: common-services.yml
        service: baseweb
    links:
        - redis
        - omeroserver
    volumes:
        - "./${BUILD_NAME}/src:/home/omero"

nginx:
    extends:
        file: common-services.yml
        service: basenginx
    links:
        - omeroweb
    volumes:
        - "./${BUILD_NAME}/src:/home/omero"
        - "./${BUILD_NAME}/nginx/log:/var/log/nginx"
        - "./${BUILD_NAME}/nginx/sslcert:/etc/nginx/ssl"
    ports:
        - "80:80"
        - "443:443"
