# DOCKER for Mac: use local postgres `ifconfig lo0 alias 192.168.100.100`
pg95:
    image: postgres
    volumes:
        - ./src/pgdata:/var/lib/postgresql/data


omeroserver:
    extends:
        file: common-services.yml
        service: baseomero
    links:
        - pg95
    volumes:
        - "./src/dist/OMERO.server:/home/omero/OMERO.server"
        - "./src/data:/home/omero/data"
        - "${PWD}/config/omeroserver.config:/home/omero/omero.config"
    env_file:
        - server.env
    ports:
        - "4064:4064"
        - "4063:4063"
#    extra_hosts:
#        - "pg95:192.168.100.100"

redis:
    image: redis


omeroweb:
    extends:
        file: common-services.yml
        service: baseweb
    links:
        - omeroserver
        - redis
    volumes:
        - "./src/omero.git:/home/omero/src"
        - "./src/webapp.git:/home/omero/webapp"
        - "./src/dist/OMERO.py:/home/omero/OMERO.py"
        - "./src/dist/static:/home/omero/static"
        - "${PWD}/config/omeroweb.config:/home/omero/omeroweb.config"
        - "${PWD}/config/requirements-webapps.txt:/home/omero/requirements-webapps.txt"
        - "./src/nginx/conf.d:/home/omero/conf.d"
    ports:
        - "4080:4080"
    env_file:
        - web.env


nginx:
    extends:
        file: common-services.yml
        service: basenginx
    links:
        - omeroweb
    volumes:
        - "./src/dist/OMERO.py:/home/omero/OMERO.py"
        - "./src/nginx/conf.d:/etc/nginx/conf.d"
        - "./src/dist/static:/home/omero/static"
        - "./src/nginx/log:/var/log/nginx"
#        - "./src/nginx/sslcert:/etc/nginx/ssl"
    ports:
        - "80:80"
#        - "443:443"
