#!/bin/bash

# build omero

set -eux

PATHDIR=`dirname $0`
DOCKER_BIN="docker exec $SERVER_NAME"
BF_PREFIX=/home/omero/bf.git
OMERO_PREFIX=/home/omero/omero.git/dist

source "$PATHDIR/inc/stop.sh"
source "$PATHDIR/inc/remove_symlinks.sh"

$DOCKER_BIN /bin/bash -c "/home/omero/omero.git/build.py build-dev"

$DOCKER_BIN $OMERO_PREFIX/bin/omero admin rewrite

source "$PATHDIR/inc/add_symlinks.sh"
#source "$PATHDIR/inc/start.sh"